"""The translation check: C++ written from a structure description alone must make
the port's decisions (CHIA hackathon).

Both run the same traces with the OPT log on every set, which records each LLC
reference and each fill's way (NUM_WAY for a bypass). Identical logs and cycle
counts mean identical decisions; otherwise the first differing line says where.

    python3 translation_check.py --out ~/loop_out/tcheck_1           # generate, build, compare
    python3 translation_check.py --out ~/loop_out/tcheck_1 --reuse   # compare the C++ already there
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from concurrent.futures import ThreadPoolExecutor
from itertools import zip_longest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import cpp_writer  # noqa: E402
from candidate import CHAMPSIM, module_sources, seed_sources  # noqa: E402
from chia_llc_loop import absent, build, trace_path  # noqa: E402
from chia_node.champsim import run_simulation  # noqa: E402

REF, GEN = "ref_port", "gen_policy"
ALL_SETS = 4096
END = "(end of log)"


def first_difference(a: Path, b: Path) -> dict:
    """The first line where two logs differ, and how many lines differ in all.
    A line the shorter log lacks counts as differing (zip would drop it)."""
    first, differing, n, len_a, len_b = None, 0, 0, 0, 0
    with open(a) as fa, open(b) as fb:
        for n, (la, lb) in enumerate(zip_longest(fa, fb), 1):
            len_a += la is not None
            len_b += lb is not None
            if la != lb:
                differing += 1
                if first is None:
                    first = {"line": n, "port": END if la is None else la.rstrip(),
                             "generated": END if lb is None else lb.rstrip()}
    return {"lines": n, "differing": differing, "first": first, "length_port": len_a, "length_generated": len_b}


def bypasses(log: Path, ways: int) -> int:
    """Fills logged with way == NUM_WAY."""
    return sum(1 for line in open(log) if line.startswith("F") and line.split()[2] == str(ways))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--yaml", type=Path, default=CHAMPSIM / "structure_description" / "policies" / "mockingjay.yaml")
    ap.add_argument("--port", default="mockingjay", help="the module the C++ must match")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--reuse", action="store_true", help="compare the C++ already in --out")
    ap.add_argument("--keep-logs", action="store_true", help="keep the OPT logs, to diagnose a difference")
    ap.add_argument("--traces", nargs="+", default=["429.mcf-192B", "483.xalancbmk-127B", "450.soplex-247B"])
    ap.add_argument("--warmup", type=int, default=1_000_000)
    ap.add_argument("--sim", type=int, default=5_000_000)
    ap.add_argument("--run-timeout", type=int, default=1800, help="seconds allowed per simulation")
    ap.add_argument("--model", default="gemini-2.5-flash")
    ap.add_argument("--max-tokens", type=int, default=32_000)
    ap.add_argument("--llm-timeout", type=int, default=300)
    ap.add_argument("--llm-retries", type=int, default=1)
    ap.add_argument("--repairs", type=int, default=2, help="capped calls that fix a module that did not compile")
    args = ap.parse_args()
    out = args.out
    out.mkdir(parents=True, exist_ok=True)

    missing = absent(args.traces)
    if missing:
        print(f"traces not on this machine: {', '.join(missing)}")
        return 1

    if not args.reuse:
        try:
            got = cpp_writer.generate(args.yaml.read_text(), model=args.model, max_tokens=args.max_tokens,
                                     timeout=args.llm_timeout, retries=args.llm_retries)
        except cpp_writer.Unusable as exc:
            cpp_writer.save(exc.got, out)
            print(f"unusable reply ({exc}); kept in {out / 'reply.txt'}")
            return 2
        cpp_writer.save(got, out)
        print(f"generated by {args.model} in {got['seconds']} s, usage {got['usage']}")

    # ChampSim compiles every module folder in the tree, so a generated module that
    # does not compile would break the port's build too: build it first, and
    # remove it if it fails.
    def build_generated():
        b = build(GEN, module_sources((out / "policy.h").read_text(), (out / "policy.cc").read_text(), GEN))
        (out / "build.txt").write_text(b.build_diagnostics or "ok")
        return b

    gen, repairs, reply = build_generated(), 0, out / "reply.txt"
    while not gen.success and repairs < args.repairs:
        repairs += 1
        kept = out / f"before_repair_{repairs}"
        kept.mkdir(exist_ok=True)
        for f in ("policy.h", "policy.cc", "build.txt"):
            shutil.copy(out / f, kept / f)
        print(f"the generated C++ did not build; repair {repairs} of {args.repairs}")
        try:
            got = cpp_writer.repair(args.yaml.read_text(), reply.read_text(), gen.build_diagnostics.replace(GEN, "@MODULE@"),
                                   model=args.model, max_tokens=args.max_tokens, timeout=args.llm_timeout,
                                   retries=args.llm_retries)
        except cpp_writer.Unusable as exc:
            cpp_writer.save(exc.got, out, prefix=f"repair_{repairs}_")
            print(f"unusable repair ({exc})")
            break
        cpp_writer.save(got, out, prefix=f"repair_{repairs}_")
        reply = out / f"repair_{repairs}_reply.txt"
        print(f"repaired by {args.model} in {got['seconds']} s, usage {got['usage']}")
        gen = build_generated()
    if not gen.success:
        shutil.rmtree(CHAMPSIM / "replacement" / GEN, ignore_errors=True)
        print(f"the generated C++ did not build:\n{gen.build_diagnostics[-3000:]}")
        return 2
    ref = build(REF, seed_sources(args.port, REF))
    if not ref.success:
        print(f"the port did not build:\n{ref.build_diagnostics}")
        return 1
    ways = ref.config["LLC"]["ways"]

    def one(job):
        tag, binary, stem = job
        log = out / f"{tag}.{stem}.opt.log"
        r = run_simulation(binary, trace_path(stem), warmup_instructions=args.warmup,
                           simulation_instructions=args.sim, timeout_s=args.run_timeout,
                           opt_log=str(log), opt_sets=ALL_SETS)
        return tag, stem, r, log

    jobs = [(tag, b.binary, s) for tag, b in (("port", ref), ("generated", gen)) for s in args.traces]
    with ThreadPoolExecutor(max_workers=len(jobs)) as pool:
        runs = {(tag, stem): (r, log) for tag, stem, r, log in pool.map(one, jobs)}

    report, same = {}, True
    for stem in args.traces:
        (rp, lp), (rg, lg) = runs[("port", stem)], runs[("generated", stem)]
        entry = {"port_ok": rp.success, "generated_ok": rg.success}
        if rp.success and rg.success:
            entry.update(cycles=(rp.cycles, rg.cycles), instructions=(rp.instructions, rg.instructions),
                         bypasses_in_port=bypasses(lp, ways), log=first_difference(lp, lg))
            entry["identical"] = rp.cycles == rg.cycles and entry["log"]["differing"] == 0
        else:
            entry["identical"] = False
            entry["tail"] = (rg if rp.success else rp).stdout_tail[-1500:]
        same &= entry["identical"]
        report[stem] = entry
        verdict = "IDENTICAL" if entry["identical"] else "DIFFERENT"
        detail = (f"{entry['log']['lines']} log lines, {entry['log']['differing']} differ, "
                  f"{entry['bypasses_in_port']} bypasses in the port, cycles {entry['cycles']}"
                  if "log" in entry else "a run failed")
        print(f"  {stem:22s} {verdict}  {detail}")
        if "log" in entry and entry["log"]["first"]:
            f = entry["log"]["first"]
            print(f"      first difference, line {f['line']}:\n        port:      {f['port']}\n        generated: {f['generated']}")
    (out / "report.json").write_text(json.dumps(report, indent=2))
    for p in [] if args.keep_logs else out.glob("*.opt.log"):
        p.unlink()  # hundreds of MB; the report keeps what matters
    print(f"repairs: {repairs}")
    print("PASS: the generated C++ makes the port's decisions" if same else "FAIL")
    return 0 if same else 3


if __name__ == "__main__":
    raise SystemExit(main())
